unbind r
bind r source-file ~/.config/tmux/tmux.conf

set -g mouse on
unbind -T copy-mode-vi MouseDragEnd1Pane

bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection

setw -g mode-keys vi

set -g default-terminal "screen-256color"
set -g prefix C-a

unbind C-b
bind-key C-a send-prefix

unbind %
bind | split-window -h

unbind '"'
bind - split-window -v

bind -r m resize-pane -Z

set-option -g status-position bottom

# set plugin
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'catppuccin/tmux'
set -g @plugin 'tmux-plugins/tmux-cpu'

# ====================================
#
# Theme configuration
## Options to make tmux more pleasant
set -g mouse on
set -g default-terminal "tmux-256color"

# Configure the catppuccin plugin
set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "rounded"
# set -g @catppuccin_status_modules_right "directory user host session cpu"

# For TPM, instead use `run ~/.config/tmux/plugins/tmux/catppuccin.tmux`

# Make the status line pretty and add some modules
set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_application}"
set -agF status-right "#{E:@catppuccin_status_cpu}"
set -ag status-right '| #{ram_percentage} '
set -ag status-right "#{E:@catppuccin_status_uptime}"

set -g @catppuccin_window_current_text " #W"
set -g @catppuccin_window_text " #W"


run ~/.config/tmux/plugins/tmux-cpu/cpu.tmux
# Or, if using TPM, just run TPM
#
#
# ============ END THEME ==============
#
#
# Initialize tmux plugin manager (line must be at the bottom of the file)
run '~/.config/tmux/plugins/tpm/tpm'
